In [1]:
% matplotlib inline

import matplotlib.pyplot as plt
import pandas as pd

from sklearn import tree

from L5.validation import confusion_matrix, print_scores

In [2]:
data = pd.read_csv("L5/data/agaricus-lepiota.data", header=None)
data.head()

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>0</th>
      <th>1</th>
      <th>2</th>
      <th>3</th>
      <th>4</th>
      <th>5</th>
      <th>6</th>
      <th>7</th>
      <th>8</th>
      <th>9</th>
      <th>...</th>
      <th>13</th>
      <th>14</th>
      <th>15</th>
      <th>16</th>
      <th>17</th>
      <th>18</th>
      <th>19</th>
      <th>20</th>
      <th>21</th>
      <th>22</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>p</td>
      <td>x</td>
      <td>s</td>
      <td>n</td>
      <td>t</td>
      <td>p</td>
      <td>f</td>
      <td>c</td>
      <td>n</td>
      <td>k</td>
      <td>...</td>
      <td>s</td>
      <td>w</td>
      <td>w</td>
      <td>p</td>
      <td>w</td>
      <td>o</td>
      <td>p</td>
      <td>k</td>
      <td>s</td>
      <td>u</td>
    </tr>
    <tr>
      <th>1</th>
      <td>e</td>
      <td>x</td>
      <td>s</td>
      <td>y</td>
      <td>t</td>
      <td>a</td>
      <td>f</td>
      <td>c</td>
      <td>b</td>
      <td>k</td>
      <td>...</td>
      <td>s</td>
      <td>w</td>
      <td>w</td>
      <td>p</td>
      <td>w</td>
      <td>o</td>
      <td>p</td>
      <td>n</td>
      <td>n</td>
      <td>g</td>
    </tr>
    <tr>
      <th>2</th>
      <td>e</td>
      <td>b</td>
      <td>s</td>
      <td>w</td>
      <td>t</td>
      <td>l</td>
      <td>f</td>
      <td>c</td>
      <td>b</td>
      <td>n</td>
      <td>...</td>
      <td>s</td>
      <td>w</td>
      <td>w</td>
      <td>p</td>
      <td>w</td>
      <td>o</td>
      <td>p</td>
      <td>n</td>
      <td>n</td>
      <td>m</td>
    </tr>
    <tr>
      <th>3</th>
      <td>p</td>
      <td>x</td>
      <td>y</td>
      <td>w</td>
      <td>t</td>
      <td>p</td>
      <td>f</td>
      <td>c</td>
      <td>n</td>
      <td>n</td>
      <td>...</td>
      <td>s</td>
      <td>w</td>
      <td>w</td>
      <td>p</td>
      <td>w</td>
      <td>o</td>
      <td>p</td>
      <td>k</td>
      <td>s</td>
      <td>u</td>
    </tr>
    <tr>
      <th>4</th>
      <td>e</td>
      <td>x</td>
      <td>s</td>
      <td>g</td>
      <td>f</td>
      <td>n</td>
      <td>f</td>
      <td>w</td>
      <td>b</td>
      <td>k</td>
      <td>...</td>
      <td>s</td>
      <td>w</td>
      <td>w</td>
      <td>p</td>
      <td>w</td>
      <td>o</td>
      <td>e</td>
      <td>n</td>
      <td>a</td>
      <td>g</td>
    </tr>
  </tbody>
</table>
<p>5 rows × 23 columns</p>
</div>

In [3]:
data = data.apply(lambda x: pd.Categorical(x).codes)
data.head()

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>0</th>
      <th>1</th>
      <th>2</th>
      <th>3</th>
      <th>4</th>
      <th>5</th>
      <th>6</th>
      <th>7</th>
      <th>8</th>
      <th>9</th>
      <th>...</th>
      <th>13</th>
      <th>14</th>
      <th>15</th>
      <th>16</th>
      <th>17</th>
      <th>18</th>
      <th>19</th>
      <th>20</th>
      <th>21</th>
      <th>22</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>5</td>
      <td>2</td>
      <td>4</td>
      <td>1</td>
      <td>6</td>
      <td>1</td>
      <td>0</td>
      <td>1</td>
      <td>4</td>
      <td>...</td>
      <td>2</td>
      <td>7</td>
      <td>7</td>
      <td>0</td>
      <td>2</td>
      <td>1</td>
      <td>4</td>
      <td>2</td>
      <td>3</td>
      <td>5</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0</td>
      <td>5</td>
      <td>2</td>
      <td>9</td>
      <td>1</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>4</td>
      <td>...</td>
      <td>2</td>
      <td>7</td>
      <td>7</td>
      <td>0</td>
      <td>2</td>
      <td>1</td>
      <td>4</td>
      <td>3</td>
      <td>2</td>
      <td>1</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0</td>
      <td>0</td>
      <td>2</td>
      <td>8</td>
      <td>1</td>
      <td>3</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>5</td>
      <td>...</td>
      <td>2</td>
      <td>7</td>
      <td>7</td>
      <td>0</td>
      <td>2</td>
      <td>1</td>
      <td>4</td>
      <td>3</td>
      <td>2</td>
      <td>3</td>
    </tr>
    <tr>
      <th>3</th>
      <td>1</td>
      <td>5</td>
      <td>3</td>
      <td>8</td>
      <td>1</td>
      <td>6</td>
      <td>1</td>
      <td>0</td>
      <td>1</td>
      <td>5</td>
      <td>...</td>
      <td>2</td>
      <td>7</td>
      <td>7</td>
      <td>0</td>
      <td>2</td>
      <td>1</td>
      <td>4</td>
      <td>2</td>
      <td>3</td>
      <td>5</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0</td>
      <td>5</td>
      <td>2</td>
      <td>3</td>
      <td>0</td>
      <td>5</td>
      <td>1</td>
      <td>1</td>
      <td>0</td>
      <td>4</td>
      <td>...</td>
      <td>2</td>
      <td>7</td>
      <td>7</td>
      <td>0</td>
      <td>2</td>
      <td>1</td>
      <td>0</td>
      <td>3</td>
      <td>0</td>
      <td>1</td>
    </tr>
  </tbody>
</table>
<p>5 rows × 23 columns</p>
</div>

In [4]:
mushroom_labels = data[0].values
mushroom_data = data.drop([0], axis = 1).values

In [5]:
for max_leaf_nodes in range(10, 21, 2):
    classifier = tree.DecisionTreeClassifier(max_leaf_nodes=max_leaf_nodes)
    print_scores(classifier, mushroom_data, mushroom_labels, max_leaf_nodes)

10: 0.971935007386
[1.0, 1.0, 0.96063960639606394, 0.97660098522167482, 0.85854858548585489, 0.98891625615763545, 0.89655172413793105, 0.96186961869618692, 1.0, 0.96678966789667897]
0.960991644399


12: 0.988675529296

[1.0, 1.0, 0.99876998769987702, 0.97660098522167482, 0.92004920049200489, 0.9926108374384236, 0.89655172413793105, 0.97662976629766296, 1.0, 0.96678966789667897]
0.972800216918


14: 0.992614475628
[1.0, 1.0, 1.0, 0.99137931034482762, 0.9372693726937269, 0.99384236453201968, 0.94211822660098521, 0.97662976629766296, 1.0, 0.99261992619926198]
0.983385896667


16: 0.994583948794

[1.0, 1.0, 1.0, 1.0, 0.9372693726937269, 0.99630541871921185, 0.95320197044334976, 0.97785977859778594, 1.0, 0.99261992619926198]
0.985725646665


18: 0.996061053668
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.96182266009852213, 0.98646986469864695, 1.0, 1.0]
0.99482925248


20: 1.0

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.96798029556650245, 1.0, 1.0, 1.0]
0.996798029557

In [6]:
for max_leaf_nodes in range(10, 21, 2):
    classifier = tree.DecisionTreeClassifier(max_leaf_nodes=max_leaf_nodes, criterion="entropy")
    print_scores(classifier, mushroom_data, mushroom_labels, max_leaf_nodes)

10: 0.982274741507
[1.0, 1.0, 0.99384993849938497, 1.0, 1.0, 1.0, 0.93103448275862066, 0.955719557195572, 1.0, 0.96678966789667897]
0.984739364635


12: 0.999015263417
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.97047970479704793, 1.0, 0.95202952029520294]
0.992250922509


14:

1.0
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.99261992619926198, 1.0, 0.95940959409594095]
0.99520295203


16: 1.0

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.99876998769987702, 1.0, 0.95940959409594095]
0.99581795818


18: 1.0
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.99507995079950795]
0.99950799508


20: 1.0

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
1.0

In [7]:
mushroom_tree = (tree.DecisionTreeClassifier(max_leaf_nodes=20, criterion="entropy")
        .fit(mushroom_data, mushroom_labels))
with open("L5/trees/mushroom.dot", "w") as f:
    tree.export_graphviz(mushroom_tree, out_file=f)

In [9]:
confusion_matrix(
    tree.DecisionTreeClassifier(max_leaf_nodes=20, criterion="entropy"), 
    mushroom_data,
    mushroom_labels
)

array([[2775,    0],
       [   0, 2641]])